### ISSUE TITLE
Send email to requester

### ISSUE THREAD

**Issue by pascalalfadian** [ftisunpar/BlueTape#15]
To go green!

**Comment by pascalalfadian** [comment]
implemented in Perubahan Jadwal Kuliah

**Comment by chez14** [comment]
Is the email notification is intended for Transcript Requester or for other feature?

**Comment by pascalalfadian** [comment]
Simply for the transcript requester. It should be very easy, I just don't have the time to implement it.

Previously I avoid this because email sending was using my personal account. Now we are using mailgun so it's fine.

**Comment by chez14** [comment]
Ohh, I see.... well I need this feature too since I often forgot to recheck the site. I'll give it a try then hehe...

**Comment by pascalalfadian** [comment]
Cool! Thanks a lot, and I will wait for your pull request

**Comment by chez14** [comment]
I've added PR #21

**Comment by pascalalfadian** [comment]
Almost perfect! Please do a minor revision as stated in PR.

**Comment by chez14** [comment]
Btw sorry, I found no comments there, is it just me or it's hidden somewhere?
![image](https://user-images.githubusercontent.com/5555026/31715925-0147015c-b430-11e7-858f-ff33a98bbd3c.png)

**Comment by pascalalfadian** [comment]
Can you try this <https://github.com/ftisunpar/BlueTape/pull/21#pullrequestreview-70098938>

**Comment by chez14** [comment]
That's strange, i even turned off my Tampermonkey to release the Github Dark CSS... and still, nothing comes up...

![image](https://user-images.githubusercontent.com/5555026/31745635-cd7a023a-b48d-11e7-94d4-d147f89ff1cd.png)

**Comment by pascalalfadian** [comment]
Really really sorry. I should have clicked a button called "submit review"

**Comment by chez14** [comment]
No worries hahaha, i didn't know that should be done either xD...

I've updated the code... hehe

**Comment by pascalalfadian** [comment]
merged and tested. works like a charm! Thanks!
