### ISSUE TITLE
Penamaan Tab pada Excel hasil Ekspor

### ISSUE THREAD

**Issue by pascalalfadian** [ftisunpar/BlueTape#16]
Dari XLS hasil ekspor, terutama pada saat "Lihat Jadwal Dosen", mohon:

1. Menghapus kata Jadwal (~~Jadwal~~ Pascal Alfadian) dari sheets
2. Menghapus sheet kosong "Worksheet"
3. Nama file diubah menjadi `JadwalDosen-YYYYMMDD.xls` di mana YYYY adalah tahun, MM bulan (selalu 2 dijit), DD tanggal (selalu 2 dijit)

Assign balik issue ini ke saya kalau sudah (saya yang close)

Trims.

**Comment by AdrianReynaldi** [comment]
Semuanya sudah saya ubah pada commit saya yang terkahir. 

Terima kasih.

**Comment by pascalalfadian** [comment]
Trims!

**Comment by pascalalfadian** [comment]
Untuk poin 3, ada bug di kode kamu, sehingga yang dihasilkan bukan diakhiri `.xlsx` melainkan `xlsx` (kurang titik `.`). Mohon diperbaiki.

![2017-09-06](https://user-images.githubusercontent.com/5976057/30102505-1618806a-931a-11e7-965b-fa860656a890.png)
