### ISSUE TITLE
File Excel Error dan Tab Bu Mariskha tidak muncul

### ISSUE THREAD

**Issue by pascalalfadian** [ftisunpar/BlueTape#17]
Halo Adrian,

Kalau saya buka XLSX hasil export, itu ada 2 masalah:

1. Ada warning "We found some problems... Do you want to try to recover?"
2. Ada laporan dari Bu Mariskha, sheet beliau tidak muncul.

Tolong dilihat dan diperbaiki ya. Mungkin ada hubungannya juga dengan #16 

![2017-09-08 1](https://user-images.githubusercontent.com/5976057/30193852-ef65d312-9479-11e7-8739-38a62a096f25.png)
![2017-09-08 2](https://user-images.githubusercontent.com/5976057/30193851-ef586f1a-9479-11e7-87b5-d6476cdf568c.png)

**Comment by AdrianReynaldi** [comment]
Issue #16 dan issue #17 sudah selesai saya perbaiki pada commit-commit tanggal 13 September 2017

**Comment by pascalalfadian** [comment]
Trims.. Ini jadi sekarang export nya ke XLS (versi lama) ya, sebagai ganti XLSX (versi baru)? Apakah karena XLSX ada bug?

**Comment by AdrianReynaldi** [comment]
Iya, karena bila menggunakan .xlsx selalu ada report yang mengatakan ada "mergecell" yang dihapus. Saya hanya ubah filenya ke tipe .xls  report tersebut langsung hilang. 

Baca-baca dari hasil googling katanya memang akan muncul report tersebut bila menggunakan .xlsx , bug dari phpExcel itu sendiri.

⁣

**Comment by AdrianReynaldi** [comment]
Sudah saya bandingkan juga jadwal yang ditampilkan di website dan di excel masih sama. Lalu saya periksa juga tampilan di Excel ketika masih menggunakan .xlsx dan setelah menggunakan .xls tidak ada perubahan sama sekali.


⁣

**Comment by pascalalfadian** [comment]
Sipp.. thanks ya.

**Comment by AdrianReynaldi** [comment]
Sama-sama pak :)

⁣Sent from BlueMail ​

**Comment by pascalalfadian** [comment]
Eh tapi koq sekarang malah ga bisa dibuka ya? Di tempat kamu bisa?

![screen shot 2017-09-13 at 15 10 56](https://user-images.githubusercontent.com/5976057/30366616-d5313688-9895-11e7-8eda-6f6b000f34f3.png)
![screen shot 2017-09-13 at 15 10 54](https://user-images.githubusercontent.com/5976057/30366615-d52e17aa-9895-11e7-84a1-b2fd1af6187e.png)

**Comment by AdrianReynaldi** [comment]
Bisa pak, tidak muncul eror apa

Sent from BlueMail 

On 13 Sep 2017, at 15:12, Pascal <notifications@github.com> wrote:
Eh tapi koq sekarang malah ga bisa dibuka ya? Di tempat kamu bisa?

**Comment by pascalalfadian** [comment]
Aneh.. Kamu coba di azure (server) atau di lokal? Ini yang saya dapatkan dari azure.
[JadwalDosen-20170913.xls.zip](https://github.com/ftisunpar/BlueTape/files/1298724/JadwalDosen-20170913.xls.zip)

**Comment by AdrianReynaldi** [comment]
Saya coba yang di azure. Tapi ternyata saya coba buka di komputer lain juga dibilang "corrupted", saya coba perbaiki lagi kalau begitu.

⁣

**Comment by AdrianReynaldi** [comment]
Sudah saya perbaiki erornya.

note :
Tadi saya coba download filenya di komputer yang sama , tapi menggunakan browser yang berbeda pun ternyata menghasilkan file "corrupt" yang tidak bisa dibuka.
Setelah saya telusuri ternyata memasukan nilai ke dalam session menggunakan cara CI "$this->session->set_userdata(array); " hanya berjalan tanpa eror di browser Chrome, ketika dbuka melalui browser lain akan menjadi error. Setelah saya ubah menjadi menggunakan $_SESSION[] biasa, eror-eror di browser lain hilang.

**Comment by pascalalfadian** [comment]
Error nya dalam arti datanya hilang, atau muncul pesan kesalahan?

**Comment by AdrianReynaldi** [comment]
Muncul pesan kesalahan "invalid argument supplied for foreach() at line 56"

Lalu saya lihat yg menssuply argumennya adalah session "dataJadwalPerUser"
⁣

**Comment by pascalalfadian** [comment]
Oke, berarti workaround nya sementara bisa pakai itu, tetapi sementara kamu mesti bisa perbaiki ini juga. Karena berarti ada yang salah di kode kamu. Coba di debug:

* `dataJadwalPerUser` isinya apa? false? null? array? dll..
* Apa yang dibutuhkan oleh `$this->sesion->set_userdata()`? apakah sudah sesuai?
* Kejadian ini terjadi saat apa saja? Setiap saat? skenario tertentu.

Intinya kamu harus tetap menggunakan `set_userdata()` tanpa ada error.

Sekalian deh kita bimbingan yuk, di minggu depan atau dua minggu lagi (target bug ini sudah beres). Coba usulkan waktunya via email `@unpar.ac.id` saja, berdasarkan jadwal saya yang sudah ada di BlueTape. Trims.
