### ISSUE TITLE
Implement "Conlict Checker" 

### ISSUE THREAD

**Issue by AdrianReynaldi** [ftisunpar/BlueTape#22]
Menambahkan fitur untuk mengecek konflik. Misalkan user memasukan jadwal pada pukul 7 dengan durasi 3 jam, berarti sistem harus memeriksa apakah ada jadwal lain diantara jam 7 sampai jam 10. Jika ada jadwal lain munculkan pop-up peringatan "jadwal tidak dapat dimasukan karena sudah ada jadwal lain".

**Comment by pascalalfadian** [comment]
Ngomong2 ini statusnya udah implemented ya? Kalau sudah tolong bantu close issue ini ya..
