### ISSUE TITLE
Input from Mariskha

### ISSUE THREAD

**Issue by pascalalfadian** [ftisunpar/BlueTape#23]
Halo @AdrianReynaldi 

Apa kabar? Bisa bantuin sedikit, ada request dari kajur nih:

1. Di tab Lihat Jadwal Dosen, itu kan sudah ada Export ke XLS, yang mengekspor jadwal seluruh dosen. Bisa ga ditambahkan di tab Entri Jadwal Dosen, tambahkan juga Export XLS, tetapi bedanya yang di ekspor jadwal dosen yang lagi login saja.
2. Sekalian kamu nanti testing-testing, kalau sudah selesai mohon entri kamu punya di bluetape dihapus ya? Ini berarti kayaknya kamu mesti masukin akses kamu lagi.

Trims;  
Pascal

**Comment by AdrianReynaldi** [comment]
-Sudah saya tambahkan tombol Ekspor XLS baru untuk dosen yang login saja.
-Entri saya sudah dihapus dan roles saya juga sudah saya hilangkan dari roles dosen

**Comment by pascalalfadian** [comment]
Terima kasih banyak ya Adrian!

**Comment by AdrianReynaldi** [comment]
oke, sama-sama pak
