### ISSUE TITLE
Support for DPS Softcopy

### ISSUE THREAD

**Issue by chez14** [ftisunpar/BlueTape#24]
As mentioned on [BKA Site](http://bka.unpar.ac.id/beasiswa/unpar1819/) (Pg. 4, Gambar 5), the scholarship submission are now done in a [site (currently can be accessed only at UNPAR's network)](http://beasiswa.unpar.ac.id/). So there's a redundant work to ask for DPS print-out, scan the paper, then submit the pdf/image to the site (oh actually they can access the GPA anyway, and doing this doesn't make any sense).

So is there a way we could support sending out the DPS paper just the PDF/Image to... let's say, our email?

**Comment by pascalalfadian** [comment]
Thanks for this input, Chris.

Correct me if I'm wrong, but as per previous rules, the printed DPS needs to be signed and stamped by the faculty before it's accepted by BKA or other departments. In this case, you mean the Tata Usaha staff will need to print it, sign and stamp it, then re-scan it and upload to the BlueTape, in which BlueTape sends it back to the student?

**Comment by chez14** [comment]
Oh i forgot the "sign and stamp" rule hahah, i think it was "print and attach".
I don't want the Tata Usaha staff do the rescan.

Oh then, is it possible to send just the [digitally sign the document](https://acrobat.adobe.com/sea/en/sign.html) for this kind of stuff, if it's affordable by make the CA/Cert with our own?

Some refs:
- Join the Adobe ATTL member: https://helpx.adobe.com/acrobat/kb/approved-trust-list2.html
- [Requirement for that](https://helpx.adobe.com/content/dam/help/en/acrobat/kb/approved-trust-list2/_jcr_content/main-pars/download-section/download-1/aatl_technical_requirements_v2.0.pdf)

More reason to add this feature:
- Relatively easy & free to sign the docs, based on [someone's answer on internet](https://stackoverflow.com/a/10903903/4721245), we can [sign it](https://tcpdf.org/examples/example_052/) with PHP [TCPDF](https://tcpdf.org/).
- It's optional to join the Adobe ATTL member, since we can sign it within our system automatically.

**Comment by pascalalfadian** [comment]
Buying certs from Adobe I believe will get a big no from the faculty. Unless if the University that wants it (like that we spent $$$ for Microsoft subscriptions, uni-wide)

Having our own CA/Cert is actually a good idea. I tried to make this a skripsi topic few years ago, but cancelled it because "not enough coding". For me, it is a step-by-step operation:

1. Install the CA in each computers that faculty have:
    * Lab komputasi
    * Komputer dosen
    * Komputer TU
2. Train people to use certificates in daily life, e.g. signing a word document, encrypting files, etc... All certs will be trusted internally.
3. Implement this in BlueTape, as you suggested.

It will be a long way road, since you cannot do step 2 without step 1 (unless if we buy), and step 3 without step 2. Neither you nor I can work alone to achieve this, but thanks for reminding this. Will think if this can be done by other means, may be using the "penelitian" fund.

---

However, back to the question:

> Oh then, is it possible to send just the digitally sign the document for this kind of stuff, if it's affordable by make the CA/Cert with our own?

This is possible if the **readers of the document are the ones trusting the CA**. For e.g., if we (FTIS) build our own CA system, the digital signature will not be trusted by, e.g. Depdikbud, for scholarship purpose.

**Comment by chez14** [comment]
Ahh ok, i see i see... i understand how long it will take. Thanks for the feedback. I'll close this issue for now, and i'll add a little note for those who want it available for `penelitian` stuff.

Btw, fyi i actually have made a CA (self-sign, but i made it quite strong) that are installed on each computer in Lab FTIS, so.. step 1 is kinda half-way finish. I own the private key and wanted to make a quick helper to install the CA with GUI (still a plan though) and a webpage, so public can download the CA and install it, and see the document are actually trusted.

We actually made those certs to make a helper agent for the lab, but you can ask for other purpose, we'll add give you a specific OID (`1.3.6.1.4.1.`[`49732`](https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers)`.*`) to mark your cert and make the documentation public if needed to let people know what those certs are actually for.

So anyone that wanted to have this feature available, please contact your lecturer and ask a `penelitian` stuff and then ask the certs you need for your `penelitian` to @ftis-admin staff, and make your own faculty-validated cert there.

**Comment by pascalalfadian** [comment]
Interesting. Will meet you to talk about this.

On 15 May 2018, at 20.16, Chris <notifications@github.com<mailto:notifications@github.com>> wrote:


Ahh ok, i see i see... i understand how long it will take. Thanks for the feedback. I'll close this issue for now, and i'll add a little note for those who want it available for penelitian stuff.

Btw, fyi i actually have made a CA (self-sign, but i made it quite strong) that are installed on each computer in Lab FTIS, so.. step 1 is kinda half-way finish. I own the private key and wanted to make a quick helper to install the CA with GUI (still a plan though) and a webpage, so public can download the CA and install it, and see the document are actually trusted.

We actually made those certs to make a helper agent for the lab, but you can ask for other purpose, we'll add give you a specific OID (1.3.6.1.4.1.49732<https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers>.*) to mark your cert and make the documentation public if needed to let people know what those certs are actually for.

So anyone that wanted to have this feature available, please contact your lecturer and ask a penelitian stuff and then ask the certs you need for your penelitian to @ftis-admin<https://github.com/ftis-admin> staff, and make your own faculty-validated cert there.
