### ISSUE TITLE
Load Google APIs Client Library via composer

### ISSUE THREAD

**Issue by ivantedja** [ftisunpar/BlueTape#6]
Saya rasa akan lebih baik untuk meload Google APIs Client via composer karena merupakan preferred method dari Google dan mengurangi hardcode

```
cd www
composer require google/apiclient:^2.0
```

`require` di `application/models/Auth_model.php` dapat dibuang:

```
    public function __construct() {
        parent::__construct();

        // require_once 'application/libraries/ext/google-api-php-client/src/Google/autoload.php'; // buang
        $this->load->config('auth-dev');
        $this->load->config('modules');
        $this->client = new Google_Client();
        $this->client->setClientId($this->config->item('google-clientid'));
        $this->client->setClientSecret($this->config->item('google-clientsecret'));
        $this->client->setRedirectUri($this->config->item('google-redirecturi'));
        $this->client->addScope('https://www.googleapis.com/auth/userinfo.email');
        $this->client->addScope('https://www.googleapis.com/auth/userinfo.profile');
    }
```

Lalu di `application/config/config.php` nyalakan opsi untuk load library via composer

```
$config['composer_autoload'] = FALSE;
```

diganti menjadi

```
$config['composer_autoload'] = 'vendor/autoload.php'; // or FCPATH . 'vendor/autoload.php'
```

Saya tidak familiar dengan Code Igniter tapi kurang lebih begitu

Salam,
ivantedja 2006730039

**Comment by pascalalfadian** [comment]
Thanks a lot! Nanti saya coba ya.

**Comment by pascalalfadian** [comment]
Sudah coba di komputer sendiri jalan dengan baik, tapi untuk servernya kan pakai autodeploy di azure, jadi saat commit otomatis updated di sana. kalau pakai composer, masalahnya file2 `vendor` tidak ada di repo git (di-ignore) jadi tidak terupload ke server. Yang terpikir:
1. folder `vendor` di un-ignore, sehingga terupload di git. tapi masalahnya jadi file2 Google jadi terekam juga di git => percuma pakai composer
2. [buat skrip di azure](https://blogs.msdn.microsoft.com/africaapps/2014/01/28/part-1-creating-a-composer-enabled-php-website-on-windows-azure-with-git-deployment/) supaya panggil composer untuk update. saya hindari karena menjadi menambah kerepotan untuk deployment.
3. kembali ke cara lama, di mana library google sebenarnya diload pakai sistem git submodule, jadi tidak terekam apa adanya di git. azure secara otomatis mendeteksi submodule dan di load, sehingga tidak perlu buat skrip khusus.

ada ide alternatif lain?

**Comment by ivantedja** [comment]
1. saya setuju dengan implementasi sekarang, `vendor` memang biasanya di ignore
2. saya kurang familiar juga sih dengan deployment.
   tapi kalau dari segi keuntungan menggunakan composer:
   - sangat mudah untuk install 3rd party module
   - menggunakan `autoload` -> library baru di include pada saat di instantiate (panggil `new`)
3. saya baru sadar Google APIs menggunakan gitsubmodule. saya hampir tidak pernah menggunakan gitsubmodule jadi `git clone` & `git pull` nya tidak pernah sekaligus me-load gitsubmodule nya makanya waktu saya test muncul error.

mungkin perlu research untuk composer vs gitsubmodule supaya lebih clear tapi dari segi best practice rasanya composer lebih recommended

**Comment by pascalalfadian** [comment]
keduanya saya lihat ada plus minus.

di project ini saya mengutamakan development yang ringan (sedikit dependecies, makanya pakai codeigniter dibanding web framework yang lain). Composer saya rasa cocok untuk project dengan dependencies yang kompleks, sehingga lebih _worth it_ untuk menginstall composer.

Karena itu, saya putuskan di project ini sementara tetap menggunakan git submodule. Anyway terima kasih untuk perkenalannya dengan composer! Saya tentu akan mempertimbangkannya untuk project2 lain yang lebih besar.

**Comment by pascalalfadian** [comment]
Halo @ivantedja 

Masih tertarik untuk kontribusi? Setelah perkenalan dengan composer, saya coba project lain dan ternyata bisa memberi benefit. Kalau masih mau, bisa buatkan pull request seperti ini?
- Sesuai dengan usul pertama kamu, tetapi:
- `composer.*` dan `vendor/` ditaruhnya di root directory, tidak di bawah `www/` (supaya tidak bisa diakses publik)
- file-file tersebut tidak perlu di ignore, dimasukkan saja ke git. Pertimbangannya:
  - supaya yang mau kontribusi, tinggal git pull tidak perlu install composer. demikian pula di deployment server
  - menjaga sewaktu-waktu Google API tidak ada lagi (seperti [kasus ini](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/))

Bagaimana?

**Comment by ivantedja** [comment]
@pascalalfadian sangat tertarik 😄 

Nanti saya submit pull request malam ini

Sebetulnya saya kurang setuju `vendor/` di include ke dalam git tapi melihat kasus di artikel itu mengerikan juga ya 😆 

Untuk penempatan composer, nanti saya coba research dulu ya. Dari framework-framework yang pernah saya lihat, biasanya document root untuk web server diarahkan ke folder `public` (untuk repo ini berarti `www/public`. Barusan saya coba googling singkat tapi contoh yang ada memang tidak ada yang mengarahkan ke `public`

**Comment by pascalalfadian** [comment]
Thanks a lot! Ditunggu ya..

Kalau di server yang saya pakai, itu bisa dicustom dan sama saya publicnya itu memang di `www/` Kalau pakai CI justru di root nya, saya pindahin ke `www/`.

**Comment by ivantedja** [comment]
Oh ternyata saya salah perkiraan

```
laravel
    app
    bootstrap
    config
    ...
    *public
        css
        js
        ...
        index.php
        ...
    ...
    composer.json
    ...
```

document root untuk web server: `laravel/public` . `laravel/composer.json` aman, tidak bisa diakses public

saya kira code igniter juga sama

```
codeigniter
    application
    *public
        css
        img
        js
    ...
    composer.json
    ...
```

ternyata `public` di dalam codeigniter hanya berisi assets. beda fungsi folder `public` nya
