### ISSUE TITLE
getting started documentation

### ISSUE THREAD

**Issue by ivantedja** [ftisunpar/BlueTape#7]
Rasanya butuh doc untuk instalasi, dll supaya memudahkan untuk berkontribusi
- setting folder untuk session? -> waktu pertama buka saya kena suatu error, sepertinya ini perlu di define di config?
- settingan untuk config.php
- setup environment dan hubungannya dengan [database.php / database-dev.php, auth.php / auth-dev.php]
- run migration
- dummy data untuk database
- setup untuk Google APIs Client di dev environment
- English version? untuk doc dan code -> seandainya para mahasiswa ikut berkontribusi, ini bisa jadi nilai plus banget bagi merek untuk dunia kerja. mungkin perlu versi bahasa Inggris nya supaya semua orang bisa melihat kontribusi mereka

**Comment by pascalalfadian** [comment]
thanks! saat ini fokusnya masih mencari mahasiswa yang mau mengembangkan ini sebagai topik skripsi, sehingga tidak hanya satu fitur saja. next step baru bisa dikembangkan menjadi open source project yang seutuhnya (termasuk english version, ide bagus!)

**Comment by pascalalfadian** [comment]
Dikerjakan di c6b8bf4ca9859f6ac26d1192d5f038738f0f2918, tapi belum di tes. BlueTape ini bakal dipakai di skripsi, moga2 nanti mahasiswa yang membaca bisa setup guide ini. Kalau ada yang kurang / salah akan diperbaiki.

Untuk Bahasa Inggris, masih belum sanggup translate nya hehe..
